INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('A', 22);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('B', 8);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('C', 5);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('D', 3);
INSERT INTO VAT_RATE (VAT_CODE, VAT_RATE) VALUES ('E', 0);